services:
  MoE-LLaVA:
    container_name: MoE-LLaVA
    image: ghcr.io/jim60105/moe-llava:latest
    user: "1001:0"
    build:
      context: .
      dockerfile: Dockerfile
      target: final
      args:
        - UID=1001
        - MODEL_NAME=LanguageBind/MoE-LLaVA-StableLM-1.6B-4e-384
      cache_from:
        - ghcr.io/jim60105/MoE-LLaVA:cache
      cache_to:
        - type=inline
    tmpfs:
      - /tmp
    volumes:
      - .:/dataset
      - cache:/.cache
    entrypoint: [ "dumb-init", "--", "deepspeed", "--num_gpus=1", "moellava.serve.gradio_web_server" ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all

volumes:
  cache: