services:
  MoE-LLaVA:
    container_name: MoE-LLaVA
    image: ghcr.io/jim60105/MoE-LLaVA:latest
    user: "1001:0"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=1001
      cache_from:
        - ghcr.io/jim60105/MoE-LLaVA:cache
      cache_to:
        - type=inline
    tmpfs:
      - /tmp
    volumes:
      - .:/dataset
    entrypoint: [ "dumb-init", "--", "python3", "moellava.app" ]
